/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view.adm;

import data.DataBaseAcess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandre
 */
public class FaturamentoCrivoDia extends javax.swing.JFrame {
private DataBaseAcess dba;
    /**
     * Creates new form FaturamentoCrivoDia
     */
    public FaturamentoCrivoDia() {
    try {
        dba = DataBaseAcess.getInstance();
    } catch (SQLException ex) {
        Logger.getLogger(FaturamentoCrivoDia.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FaturamentoDia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        FaturamentoDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plano", "Crivadas", "Brutas", "Optou Dados", "Faturamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(FaturamentoDia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showFaturamento();
    }//GEN-LAST:event_formWindowOpened
    
    private void showFaturamento(){
        
        ArrayList<String> plano = new ArrayList<>();
        Map<String, Double> valor = new HashMap<>();
        ArrayList<String> regiao = new ArrayList<>();
        Map<String, Integer> dados = new HashMap<>();
        Map<String, Integer> crivo = new HashMap<>();
        Map<String, Integer> bruto = new HashMap<>();
        int ct = 0;
        String qry2 = "SELECT descricao, valor FROM plano";
    try {
        ResultSet rs = dba.execQry(qry2);
        while(rs.next()){
            bruto.put(rs.getString("descricao"), 0);
            crivo.put(rs.getString("descricao"), 0);
            plano.add(rs.getString("descricao"));
            valor.put(rs.getString("descricao"), rs.getDouble("valor"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(FaturamentoCrivoDia.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        String qry = "SELECT ramal, planoEscolhido, statusCrivo, fidelizadaAno, optouAppsDataFree, regiaoVenda FROM vendas";
    try {
        ResultSet rs = dba.execQry(qry);
        double fat = 0;
        while(rs.next()){
            String ramal, planoA, crivoA, fidelizado, dadosA, regiaoA;
            ramal = rs.getString("ramal");
            planoA = rs.getString("planoEscolhido");
            crivoA = rs.getString("statusCrivo");
            fidelizado = rs.getString("fidelizadaAno");
            dadosA = rs.getString("optouAppsDataFree");
            regiaoA = rs.getString("regiaoVenda");
            if(crivoA.equalsIgnoreCase("sim")){
                crivo.replace(planoA, crivo.get(planoA)+1);
                bruto.replace(planoA, bruto.get(planoA)+1);
            }else{
                bruto.replace(planoA, bruto.get(planoA)+1);
            }
        }
        Object[] row = new Object[6]; //HashMaps por 
        DefaultTableModel dm = (DefaultTableModel) FaturamentoDia.getModel();
        for(String z: plano){
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(FaturamentoCrivoDia.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturamentoCrivoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturamentoCrivoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturamentoCrivoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturamentoCrivoDia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FaturamentoCrivoDia().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FaturamentoDia;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
