/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view.supervisao;

import data.DataBaseAcess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandre
 */
public class PaLogadas extends javax.swing.JFrame {
private DataBaseAcess dba;
private ArrayList<String> operador = new ArrayList<>();
private ArrayList<String> ramal = new ArrayList<>();
private ArrayList<Integer> status = new ArrayList<>();
private DefaultTableModel dm;
    /**
     * Creates new form PaLogadas
     */
    public PaLogadas() {
    try {
        dba = DataBaseAcess.getInstance();
    } catch (SQLException ex) {
        Logger.getLogger(PaLogadas.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
        dm = (DefaultTableModel) table.getModel();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        attB = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        nPas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ARES :: Supervisão");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ramal", "Operador", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        attB.setText("Atualizar");
        attB.setEnabled(false);
        attB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attBActionPerformed(evt);
            }
        });

        lbl.setText("Total de PA's Logadas/Total de PA's:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nPas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(attB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attB)
                    .addComponent(lbl)
                    .addComponent(nPas))
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showT(){
        table.setModel(dm);
        try {
        // TODO add your handling code here:
        String qry = "SELECT ramal, nome, status FROM usuario WHERE idtipo_usuario = 6";
        ResultSet rs = dba.execQry(qry);
        while(rs.next()){            
            ramal.add(rs.getString("ramal"));
            operador.add(rs.getString("nome"));
            status.add(rs.getInt("status"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(PaLogadas.class.getName()).log(Level.SEVERE, null, ex);
    }
    
        DefaultTableModel dm = (DefaultTableModel) table.getModel();
        Object[] row = new Object[3];
        int ct = 0;
        for(int i = 0; i < ramal.size(); i++){
            row[0] = ramal.get(i);
            row[1] = operador.get(i);
            if(status.get(i) == 1){
                row[2] = "DESLOGADO";
            }else{
                row[2] = "LOGADO";
                ct++;
            }
            dm.addRow(row);
        }
        Double p = (double) ct/ramal.size();
        p = p *100;
        DecimalFormat df = new DecimalFormat(".##");
        nPas.setText(ct+"/"+ramal.size()+" "+df.format(p)+"(% Logados)");
        table.setModel(dm);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showT();
    
    }//GEN-LAST:event_formWindowOpened

    private void attBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attBActionPerformed
        // TODO add your handling code here:
        
        showT();
    }//GEN-LAST:event_attBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaLogadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaLogadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaLogadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaLogadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PaLogadas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel nPas;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
