/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view.supervisao;

import data.DataBaseAcess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandre
 */
public class PlanilhaPonto extends javax.swing.JFrame {
private DataBaseAcess dba;
    /**
     * Creates new form PlanilhaPonto
     */
    public PlanilhaPonto() {
    try {
        dba = DataBaseAcess.getInstance();
    } catch (SQLException ex) {
        Logger.getLogger(PlanilhaPonto.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tPonto = new javax.swing.JTable();
        atualizar = new javax.swing.JButton();
        semPonto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tPonto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ramal", "Operador", "Hora Login", "Hora Logout"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tPonto);

        atualizar.setText("Atualizar");
        atualizar.setEnabled(false);
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        semPonto.setText("Ramais que não bateram ponto");
        semPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semPontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(semPonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizar)
                    .addComponent(semPonto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semPontoActionPerformed
        // TODO add your handling code here:
        RamaisDeslogados v = new RamaisDeslogados();
        v.setVisible(true);
    
    }//GEN-LAST:event_semPontoActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        showT();
        
    }//GEN-LAST:event_atualizarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showT();
    }//GEN-LAST:event_formWindowOpened
    
    private void showT(){
       
        String qry = "SELECT ramal, nome FROM usuario WHERE idtipo_usuario = 6";
        Map<Integer, String> mp = new HashMap<>();
    try {
        ResultSet rs = dba.execQry(qry);
        while(rs.next()){
            mp.put(rs.getInt("ramal"), rs.getString("nome"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(PlanilhaPonto.class.getName()).log(Level.SEVERE, null, ex);
    }
        ZonedDateTime logout = ZonedDateTime.now();
        String HoraLogout = logout.format(DateTimeFormatter.ISO_LOCAL_DATE);
        System.out.println(HoraLogout);
        String qry2 = "SELECT ramal, hora_login, hora_logout FROM controle_ponto WHERE data = '"+HoraLogout+"'";
    try {
        ResultSet rs = dba.execQry(qry2);
        Object[] row = new Object[4];
        DefaultTableModel dm = (DefaultTableModel) tPonto.getModel();
        while(rs.next()){
            if(mp.containsKey(rs.getInt("ramal"))){
                row[0] = rs.getInt("ramal");
                row[1] = mp.get(rs.getInt("ramal"));
                row[2] = rs.getString("hora_login");
                row[3] = rs.getString("hora_logout");
                dm.addRow(row);
            }
        }
        tPonto.setModel(dm);
    } catch (SQLException ex) {
        Logger.getLogger(PlanilhaPonto.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanilhaPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanilhaPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanilhaPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanilhaPonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanilhaPonto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton semPonto;
    private javax.swing.JTable tPonto;
    // End of variables declaration//GEN-END:variables
}
