/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view.supervisao;


import auxiliar.RandomString;
import client.view.RelatorioVendas;
import client.view.VendasDependentes;
import controller.SipConnector;
import javax.swing.JOptionPane;
import data.*;
import java.sql.SQLException;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Alexandre Magalhães
 */
public class SupervisaoMenu extends javax.swing.JFrame {
    private DataBaseAcess dba;
    private APIAcess api;
    static private String nome;
    static private String ramal;
    private String dataLogin = ZonedDateTime.now().format(DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM));
    ZonedDateTime date = ZonedDateTime.now();
    private String dataDia = date.format(DateTimeFormatter.ISO_LOCAL_DATE);
    private String HoraLogin = date.format(DateTimeFormatter.ISO_LOCAL_TIME);
    private String idlog;
    private final RandomString session;
    /**
     * Creates new form SupervisaoMenu
     * @param nome
     * @param ramal
     */
    public SupervisaoMenu(String nome, String ramal) {
        this.nome = nome;
        this.ramal = ramal;
        try {
            api = APIAcess.getInstance();
            dba = DataBaseAcess.getInstance();
        } catch (SQLException ex) {
            Logger.getLogger(SupervisaoMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        session = new RandomString(8, ThreadLocalRandom.current());
        idlog  = session.toString().substring(session.toString().indexOf("@")+1);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuInfo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rLog = new javax.swing.JLabel();
        vCrivo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuBar1 = new javax.swing.JMenuBar();
        mSetores1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        supPonto = new javax.swing.JMenu();
        liberarLogout = new javax.swing.JMenuItem();
        supPA = new javax.swing.JMenuItem();
        gerarPonto = new javax.swing.JMenuItem();
        vendasControle = new javax.swing.JMenu();
        visualisarVendas = new javax.swing.JMenuItem();
        supDep = new javax.swing.JMenuItem();
        supVendas = new javax.swing.JMenuItem();
        rVendas = new javax.swing.JMenuItem();
        mConfig1 = new javax.swing.JMenu();
        sys1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ARES :: TELECONECTIVIDADE");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuInfo.setEditable(false);
        menuInfo.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(menuInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 259, 400, -1));

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText("Ramais Logados:");
        jLabel2.setToolTipText("");

        jLabel3.setForeground(new java.awt.Color(0, 204, 51));
        jLabel3.setText("Vendas Crivadas:");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rLog, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(vCrivo)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vCrivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/resources/bg.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mSetores1.setText("Supervisão");
        mSetores1.add(jSeparator2);

        supPonto.setText("Controle de Ponto");

        liberarLogout.setText("Liberar Logout");
        liberarLogout.setMultiClickThreshhold(1L);
        liberarLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberarLogoutActionPerformed(evt);
            }
        });
        supPonto.add(liberarLogout);

        supPA.setText("PA's Logadas");
        supPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supPAActionPerformed(evt);
            }
        });
        supPonto.add(supPA);

        gerarPonto.setText("Visualizar/Gerar Planilha de Ponto");
        gerarPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarPontoActionPerformed(evt);
            }
        });
        supPonto.add(gerarPonto);

        mSetores1.add(supPonto);

        vendasControle.setText("Controle de Vendas");

        visualisarVendas.setText("Visualizar/Exportar Vendas Lançadas");
        visualisarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualisarVendasActionPerformed(evt);
            }
        });
        vendasControle.add(visualisarVendas);

        supDep.setText("Visualizar Dependentes");
        supDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supDepActionPerformed(evt);
            }
        });
        vendasControle.add(supDep);

        supVendas.setText("Vendas x Planos/Aproveitamento por Região");
        supVendas.setActionCommand("");
        supVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supVendasActionPerformed(evt);
            }
        });
        vendasControle.add(supVendas);

        mSetores1.add(vendasControle);

        rVendas.setText("Juntar Planilhas");
        rVendas.setEnabled(false);
        rVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rVendasActionPerformed(evt);
            }
        });
        mSetores1.add(rVendas);

        MenuBar1.add(mSetores1);

        mConfig1.setText("Configurações");
        mConfig1.setEnabled(false);
        MenuBar1.add(mConfig1);

        sys1.setText("Sobre");
        sys1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sys1ActionPerformed(evt);
            }
        });
        MenuBar1.add(sys1);

        setJMenuBar(MenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void liberarLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberarLogoutActionPerformed
        try {
            dba = DataBaseAcess.getInstance();
            //supervisao_controle UPDATE autorizar S
            //String answ;
            //answ = JOptionPane.showInputDialog("Deseja liberar o logout dos operadores?");
            int a = JOptionPane.showConfirmDialog(this, "Deseja liberar LOGOUT parar sua equipe?", "ARES :: Teleconectividade", JOptionPane.YES_NO_OPTION);
            switch(a){
                case 0:
                    dba.execute("UPDATE supervisao_controle SET autorizar = 'S' WHERE id_operador = 1");
                    break;
                case 1:
                    dba.execute("UPDATE supervisao_controle SET autorizar = 'N' WHERE id_operador = 1");
                    break;
                default:
                    break;
            }
            //0 OK
            //2 Cancel
            //-1 Exit
        } catch (SQLException ex) {
            Logger.getLogger(SupervisaoMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_liberarLogoutActionPerformed

    private void rVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rVendasActionPerformed
    
    }//GEN-LAST:event_rVendasActionPerformed

    private void sys1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sys1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sys1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        menuInfo.setText(ramal+" : "+nome + " | Logado às: " + dataLogin);
        try {            
            boolean ponto = dba.execute("INSERT INTO controle_ponto (ssid, ramal, nome, data, hora_login) "
                    + "VALUES ('"+idlog+"', '"+ramal+"', '"+nome+"', '"+dataDia+"', '"+HoraLogin+"')"
            );            
            if(ponto){
               JOptionPane.showMessageDialog(this, "Hora de login registrada.\n"+HoraLogin);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SupervisaoMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        try {
           dba.execute("UPDATE usuario SET status = 1 WHERE (ramal = " + ramal + ")");
           ZonedDateTime logout = ZonedDateTime.now();
           String HoraLogout = logout.format(DateTimeFormatter.ISO_LOCAL_TIME);
           boolean ponto = dba.execute("UPDATE controle_ponto SET hora_logout = '"+HoraLogout+"' WHERE (ssid = '" + idlog + "')");         
           if(ponto){
               JOptionPane.showMessageDialog(this, "Hora de logout registrada.\n"+HoraLogout);
           }
        } catch (SQLException ex) {
            Logger.getLogger(SupervisaoMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dba.closeConnnection();
        SipConnector sip = new SipConnector();
        api.logout(ramal);
        sip.Logout();
        dba.closeConnnection();
        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void visualisarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualisarVendasActionPerformed
       // TODO add your handling code here:
       RelatorioVendas v = new RelatorioVendas();
       v.setVisible(true);        
    }//GEN-LAST:event_visualisarVendasActionPerformed

    private void supDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supDepActionPerformed
        // TODO add your handling code here:
        VendasDependentes v = new VendasDependentes();
        v.setVisible(true);
    }//GEN-LAST:event_supDepActionPerformed

    private void supVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supVendasActionPerformed
        // TODO add your handling code here:
        FaturamentoCrivoDia f = new FaturamentoCrivoDia();
        f.setVisible(true);
    }//GEN-LAST:event_supVendasActionPerformed

    private void supPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supPAActionPerformed
        // TODO add your handling code here:
        PaLogadas v = new PaLogadas();
        v.setVisible(true);
    }//GEN-LAST:event_supPAActionPerformed

    private void gerarPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarPontoActionPerformed
        // TODO add your handling code here:
        PlanilhaPonto v = new PlanilhaPonto();
        v.setVisible(true);
    }//GEN-LAST:event_gerarPontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupervisaoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupervisaoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupervisaoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupervisaoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SupervisaoMenu(nome, ramal).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar1;
    private javax.swing.JMenuItem gerarPonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem liberarLogout;
    private javax.swing.JMenu mConfig1;
    private javax.swing.JMenu mSetores1;
    private javax.swing.JTextField menuInfo;
    private javax.swing.JLabel rLog;
    private javax.swing.JMenuItem rVendas;
    private javax.swing.JMenuItem supDep;
    private javax.swing.JMenuItem supPA;
    private javax.swing.JMenu supPonto;
    private javax.swing.JMenuItem supVendas;
    private javax.swing.JMenu sys1;
    private javax.swing.JLabel vCrivo;
    private javax.swing.JMenu vendasControle;
    private javax.swing.JMenuItem visualisarVendas;
    // End of variables declaration//GEN-END:variables
}
