/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import auxiliar.Cronometro;
import controller.ControladorLogin;
import data.DataBaseAcess;
import java.awt.Toolkit;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import model.Usuario;

/**
 *
 * @author suporteti
 */
public class Login extends javax.swing.JFrame {
    private ControladorLogin log;
    private DataBaseAcess dba;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ramal = new javax.swing.JTextField();
        bLogin = new javax.swing.JButton();
        pwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARES :: Teleconectividade");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ramal:");
        jLabel1.setRequestFocusEnabled(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        ramal.setToolTipText("");
        ramal.setName("ramal"); // NOI18N
        ramal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramalActionPerformed(evt);
            }
        });
        getContentPane().add(ramal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 130, -1));

        bLogin.setText("Entrar");
        bLogin.setToolTipText("Java>Delphi");
        bLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bLogin.setBorderPainted(false);
        bLogin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 30));

        pwd.setToolTipText("");
        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        pwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdKeyPressed(evt);
            }
        });
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/resources/Teleconectividade.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 280, 130));

        pack();
    }//GEN-END:initComponents

    private void ramalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramalActionPerformed
        //  static String login =
    }//GEN-LAST:event_ramalActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        boolean loop = true;
            Usuario userLogin = new Usuario();
        try {
            dba = DataBaseAcess.getInstance();
            log = ControladorLogin.getInstance();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
           ResultSet logs = dba.execQry("SELECT status FROM usuario WHERE (ramal = "+ramal.getText()+")");
           if(logs.next()){               
               int a = logs.getInt("status");
               if(a == 2){throw new RuntimeException("Usuário já logado!");} 
               if(a == 0){
                   JOptionPane.showInputDialog("Você precisa redefinir sua senha!");
               };
           }
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        while(loop){            
            try {
                userLogin.setRamalLogin(ramal.getText());
                userLogin.setSenha(pwd.getText());                
                if(log.login(userLogin) == false){
                    throw new RuntimeException("Usuário ou senha incorretos!\nSe o erro persistir, contate o CPD.");
                }else{
                    
                    Menu menu = new Menu(log.getName(), userLogin.getRamalLogin());
                    menu.setVisible(true);
                    this.setVisible(false);
                    dba.execute("UPDATE usuario SET status = 2 WHERE (ramal = " + userLogin.getRamalLogin() + ")");
                    loop = false;
                }                                
            } catch (RuntimeException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ARES :: Teleconectividade", JOptionPane.ERROR_MESSAGE);               
                loop = false;
            }            
        }
        
    }//GEN-LAST:event_bLoginActionPerformed

    private void pwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdKeyPressed

    }//GEN-LAST:event_pwdKeyPressed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        bLoginActionPerformed(evt);
    }//GEN-LAST:event_pwdActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField ramal;
    // End of variables declaration//GEN-END:variables
}
