/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import client.view.operacao.Vendas;
import data.DataBaseAcess;
import java.awt.TextField;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import model.Venda;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author suporteti
 */
public class RelatorioVendas extends javax.swing.JFrame {

   DataBaseAcess dba;
   
    public RelatorioVendas() {
        initComponents();
       try {
           dba = DataBaseAcess.getInstance();
       } catch (SQLException ex) {
           Logger.getLogger(RelatorioVendas.class.getName()).log(Level.SEVERE, null, ex);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       String qry = "SELECT * FROM vendas";
       List<Venda> vendas = new ArrayList<>();
       try {
           ResultSet rs = dba.execQry(qry);
           while(rs.next()) {
               Venda v = new Venda(rs.getString("nomeOperador"), rs.getString("dataVenda"), rs.getString("regiaoVenda"), 
                     rs.getString("planoEscolhido"), rs.getString("nomeCliente"), rs.getString("cpfCliente"), rs.getString("telefone1Cliente"), 
                     rs.getString("telefone2Cliente"), rs.getString("dataNascCliente"), rs.getString("nomeMaeCliente"), rs.getInt("statusCrivo"), 
                     rs.getInt("fidelizadaAno"), rs.getInt("optouAppsDataFree"), rs.getString("cepCliente"), rs.getString("cidadeCliente"), 
                     rs.getString("estadoCliente"), rs.getString("logradouroCliente"), rs.getString("numeroCliente"), rs.getString("complementoCliente"), 
                     rs.getString("bairroCliente"), rs.getString("pontoReferencia1"), rs.getString("pontoReferencia2"), rs.getString("nomePessoaAutorizada1"), 
                     rs.getString("nomePessoaAutorizada2"), rs.getString("telefonePessoaAutorizada1"), rs.getString("telefonePessoaAutorizada2"), 
                     rs.getInt("quantidadeChipsAEnviar"), rs.getInt("boletoDigital"), rs.getString("email"), rs.getInt("optouPortabilidade"), 
                     rs.getString("portabilidadeDDD"), rs.getString("dataVencimento"), rs.getInt("aceite"), rs.getString("cepAlternativo"), 
                     rs.getString("estadoAlternativo"), rs.getString("cidadeAlternativa"), rs.getString("bairroAlternativo"), 
                     rs.getString("logradouroAlternativo"), rs.getString("numeroAlternativo"), rs.getString("complementoAlternativo"), rs.getInt("enderecoAlternativo"));
               vendas.add(v); 
           }
       } catch (SQLException ex) {
           Logger.getLogger(RelatorioVendas.class.getName()).log(Level.SEVERE, null, ex);  
       }
       String[] columns = new String [] {
                "idVenda", "Nome do operador", "Data da venda", "Região da venda", "Plano escolhido", 
            "Nome", "CPF", "Telefone 1", "Telefone 2", "Data de nascimento", "Nome da mãe", "Status do Crivo", 
           "Fidelização Ano", "Optou redes sociais", "CEP", "Cidade", "Estado", "Logradouro", "Numero", "Complemento", 
           "Bairro", "Ponto de referência 1", "Ponto de referência 2", "Nome pessoa autorizada 1", 
           "Nome pessoa autorizada 2", "Telefone pessoa autorizada 1", "Telefone pessoa autorizada 2", 
           "Quantidade chips", "Boleto Digital", "Email", "Optou portabilidade", "DDD da portabilidadel", 
           "Data de vencimento", "Estado da venda", "CEP (Alternativo)", "Estado (Alternativo)", 
           "Cidade (Alternativa)", "Bairro (Alternativo)", "Logradouro (Alternativo)", "Numero (Alternativo)", 
           "Complemento (Alternativo)", "Endereco de entrega alternativo"
            };
       
        String[] columnsDBNames = new String[] { //Array de apoio de nomes das colunas no banco
                    "idvendas", "nomeOperador", "dataVenda", "regiaoVenda", 
                    "planoEscolhido", "nomeCliente", "cpfCliente", "telefone1Cliente",
                    "telefone2Cliente", "dataNascCliente", "nomeMaeCliente", "statusCrivo", 
                    "fidelizadaAno", "optouAppsDataFree", "cepCliente", "cidadeCliente", 
                    "estadoCliente", "logradouroCliente", "numeroCliente", "complementoCliente", 
                    "bairroCliente", "pontoReferencia1", "pontoReferencia2", "nomePessoaAutorizada1", 
                    "nomePessoaAutorizada2", "telefonePessoaAutorizada1", "telefonePessoaAutorizada2", 
                    "quantidadeChipsAEnviar", "boletoDigital", "email", "optouPortabilidade", 
                    "portabilidadeDDD", "dataVencimento", "aceite", "cepAlternativo", 
                    "estadoAlternativo", "cidadeAlternativa", "bairroAlternativo", 
                    "logradouroAlternativo", "numeroAlternativo", "complementoAlternativo", "enderecoAlternativo"
           };
        
        
        System.out.println(columns.length + "   " + columnsDBNames.length);
       
       
       try {
           ResultSet rs = dba.execQry(qry);
           Object[][] rows = new Object[vendas.size()][42];
           
            for(int i = 0 ; rs.next() ; i++) {
                   for(int j = 1 ; j <= 42 ; j++) {
                       
                       if(j == 12 || j == 13 || j == 14 || j == 28 || j == 29 || j == 31 
                                    || j == 34 || j == 42)
                            rows[i][j-1] = (Integer) rs.getInt(j);
                        else
                            rows[i][j-1] = rs.getString(j);
                    }
           }
            
        DefaultTableModel tableModel = new DefaultTableModel(rows, columns);
        jTable1.setModel(tableModel);
                    
       } catch (SQLException ex) {
           Logger.getLogger(RelatorioVendas.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
