/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import data.DataBaseAcess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VendaDependente;

/**
 *
 * @author Alexandre Magalhães at amrm@cin.ufpe.br
 */
public class VendasDependentes extends javax.swing.JFrame {
    private DataBaseAcess dba;
    /**
     * Creates new form VendasDependentes
     */
    public VendasDependentes() {
        try {
            dba = DataBaseAcess.getInstance();
        } catch (SQLException ex) {
            Logger.getLogger(VendasDependentes.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tDep = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        v = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Venda", "Portabilidade", "Numero", "E-Mail", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDep);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        v.setText("Visualizar venda relacionada");
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(v)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v)
                    .addComponent(jButton1))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List<VendaDependente> vdep = new ArrayList<>();
        String qry = "SELECT * FROM vendas_dependentes";
        String qry1 = "";
        try {
            // TODO add your handling code here:
            
            ResultSet rs = dba.execQry(qry);
            while(rs.next()){
                VendaDependente v = new VendaDependente(rs.getInt("idvendas"), rs.getString("plano"), rs.getString("numero"), rs.getString("portabilidade"), rs.getString("email"), rs.getString("tipo"));
                vdep.add(v);
            }// String numero, String portabilidade, String email, String tipo
        } catch (SQLException ex) {
            Logger.getLogger(VendasDependentes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
             String[] columns = new String [] {
               "id", "Plano", "Numero", "ID Venda", "Portabilidade" ,"E-Mail", "Tipo"
            };
            ResultSet rs = dba.execQry(qry);
            Object[][] rows = new Object[vdep.size()][8];
            for(int i = 0; rs.next(); i++){
                for(int j = 1; j <= 7; j++){
                    if(j == 1 || j == 4){
                        rows[i][j-1] = (Integer) rs.getInt(j);
                    }else{
                        rows[i][j-1] = rs.getString(j);
                    }
                }
            }
            DefaultTableModel tableModel = new DefaultTableModel(rows, columns);
            tDep.setModel(tableModel);
        } catch (SQLException ex) {
            Logger.getLogger(VendasDependentes.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        // TODO add your handling code here:
        int row = tDep.getSelectedRow();
        int id = (Integer) tDep.getValueAt(row, 3);
        String qry = "SELECT nomeOperador, dataVenda, regiaoVenda, planoEscolhido, cpfCliente, operadoraOrigem FROM vendas WHERE idVendas = "+id;
        ResultSet rs;
        try {
            rs = dba.execQry(qry);
            while(rs.next()){
                String operador, data, regiao, plano, cpf, opOrigem;
                operador = rs.getString("nomeOperador");
                data = rs.getDate("dataVenda").toString();
                regiao = rs.getString("regiaoVenda");
                plano = rs.getString("planoEscolhido");
                cpf = rs.getString("cpfCliente");
                opOrigem = rs.getString("operadoraOrigem");
                String fin = "Operador: " + operador + ", Data Venda: " + data + ", Região: " + regiao  + ", Plano: " + plano + ", CPF: " + cpf + ", Op. Origem: " + opOrigem;
                JOptionPane.showMessageDialog(this, fin);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VendasDependentes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_vActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasDependentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasDependentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasDependentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasDependentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VendasDependentes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tDep;
    private javax.swing.JButton v;
    // End of variables declaration//GEN-END:variables
}
