/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view.operacao;

import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import data.DataBaseAcess;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author suporteti
 */
public class Vendas extends javax.swing.JFrame {

    static private String ramal;
    static private String nome;
    static private int idUsuario;
    private static DataBaseAcess dba;
    
    public Vendas(String ramal, String nome) {
        this.ramal = ramal;
        try {
            dba = DataBaseAcess.getInstance();
        } catch (SQLException ex) {
            Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        opField.setText(nome);
        dVenda.setText(ZonedDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        tVendas = new javax.swing.JTabbedPane();
        tDadosC1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        opField = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        cpftit = new javax.swing.JTextField();
        datanas = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        maenome = new javax.swing.JTextField();
        statusVenda = new javax.swing.JComboBox<>();
        pEnd2 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        end = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        comp = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        endif = new javax.swing.JCheckBox();
        pEnd3 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        endDif = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        nDif = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        compDif = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        bairroDif = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        cidDif = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        cepDif = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        estadoDif = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        pref1 = new javax.swing.JTextField();
        pau1 = new javax.swing.JTextField();
        ptel1 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        pref2 = new javax.swing.JTextField();
        pau2 = new javax.swing.JTextField();
        ptel2 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        tel1 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        tDadosV = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dVenda = new javax.swing.JTextField();
        campV = new javax.swing.JComboBox<>();
        resCrivo = new javax.swing.JComboBox<>();
        estadoV = new javax.swing.JComboBox<>();
        planoV = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        vencV = new javax.swing.JComboBox<>();
        tipoV = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        protocolo = new javax.swing.JTextField();
        opV = new javax.swing.JComboBox<>();
        portabilidadeV = new javax.swing.JCheckBox();
        nPortab = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        adcDependente = new javax.swing.JButton();
        removerDependente = new javax.swing.JButton();
        editarDependente = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        depTipoComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        numCelDependente = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        tipoContaDepComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        tipoPlanoDepComboBOx = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        emailDependTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        dependTable = new javax.swing.JTable();
        fidelizacaoA1 = new javax.swing.JCheckBox();
        redesSociasA1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tDadosC1.setAutoscrolls(true);
        tDadosC1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tDadosC1.setPreferredSize(new java.awt.Dimension(718, 700));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Operador:");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setText("Status da Venda:");

        opField.setEditable(false);
        opField.setAutoscrolls(false);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setText("Nome do Cliente:");

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel55.setText("CPF do Titular:");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setText("Data de Nascimento:");

        cpftit.setToolTipText("");

        datanas.setText("ano-mes-dia");
        datanas.setToolTipText("");

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel57.setText("Telefone de Contato 1:");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel58.setText("Nome da Mãe:");

        statusVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aceita pelo cliente", "Rascunho" }));
        statusVenda.setBorder(null);

        pEnd2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pEnd2.setToolTipText("");

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setText("Endereço de Cobrança:");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setText("Número:");

        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel62.setText("Complemento:");

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel63.setText("Bairro:");

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel64.setText("Cidade:");

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel65.setText("Estado:");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel59.setText("CEP:");

        jButton3.setText("G");
        jButton3.setToolTipText("Checar Cep");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pEnd2Layout = new javax.swing.GroupLayout(pEnd2);
        pEnd2.setLayout(pEnd2Layout);
        pEnd2Layout.setHorizontalGroup(
            pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnd2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addGroup(pEnd2Layout.createSequentialGroup()
                        .addComponent(jLabel63)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel64))
                    .addGroup(pEnd2Layout.createSequentialGroup()
                        .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cidade)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEnd2Layout.createSequentialGroup()
                        .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61))
                        .addGap(33, 33, 33)
                        .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEnd2Layout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(comp)))
                    .addGroup(pEnd2Layout.createSequentialGroup()
                        .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEnd2Layout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(estado))
                        .addGap(18, 18, 18)
                        .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel59)
                            .addGroup(pEnd2Layout.createSequentialGroup()
                                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pEnd2Layout.setVerticalGroup(
            pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnd2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(jLabel61)
                    .addComponent(jLabel62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEnd2Layout.createSequentialGroup()
                        .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel63)
                            .addComponent(jLabel64)
                            .addComponent(jLabel65))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pEnd2Layout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEnd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addContainerGap())
        );

        endif.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        endif.setText("Dados de Entrega do Chip Diferente da Cobrança");
        endif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endifMouseClicked(evt);
            }
        });
        endif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endifActionPerformed(evt);
            }
        });

        pEnd3.setBackground(new java.awt.Color(204, 204, 204));
        pEnd3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pEnd3.setToolTipText("");

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel66.setText("ENDEREÇO DE ENTREGA CHIP:");
        jLabel66.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jLabel66jLabel68VetoableChange(evt);
            }
        });

        endDif.setEnabled(false);
        endDif.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                endDifjLabel68VetoableChange(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel67.setText("Número:");
        jLabel67.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jLabel67jLabel68VetoableChange(evt);
            }
        });

        nDif.setEnabled(false);
        nDif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nDifActionPerformed(evt);
            }
        });
        nDif.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                nDifjLabel68VetoableChange(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel68.setText("Complemento:");

        compDif.setEnabled(false);
        compDif.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                compDifjLabel68VetoableChange(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel69.setText("Bairro:");
        jLabel69.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jLabel69jLabel68VetoableChange(evt);
            }
        });

        bairroDif.setEnabled(false);
        bairroDif.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                bairroDifjLabel68VetoableChange(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel70.setText("Cidade:");
        jLabel70.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jLabel70jLabel68VetoableChange(evt);
            }
        });

        cidDif.setEnabled(false);
        cidDif.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cidDifjLabel68VetoableChange(evt);
            }
        });

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel71.setText("CEP:");
        jLabel71.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jLabel71jLabel68VetoableChange(evt);
            }
        });

        cepDif.setEnabled(false);
        cepDif.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cepDifjLabel68VetoableChange(evt);
            }
        });

        jButton5.setText("G");
        jButton5.setToolTipText("Checar Cep");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jButton5jLabel68VetoableChange(evt);
            }
        });

        estadoDif.setEnabled(false);

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel78.setText("Estado:");

        javax.swing.GroupLayout pEnd3Layout = new javax.swing.GroupLayout(pEnd3);
        pEnd3.setLayout(pEnd3Layout);
        pEnd3Layout.setHorizontalGroup(
            pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnd3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(endDif, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66)
                    .addGroup(pEnd3Layout.createSequentialGroup()
                        .addComponent(jLabel69)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel70))
                    .addGroup(pEnd3Layout.createSequentialGroup()
                        .addComponent(bairroDif, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cidDif)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEnd3Layout.createSequentialGroup()
                        .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nDif, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(33, 33, 33)
                        .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEnd3Layout.createSequentialGroup()
                                .addComponent(jLabel68)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(compDif)))
                    .addGroup(pEnd3Layout.createSequentialGroup()
                        .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel71)
                            .addGroup(pEnd3Layout.createSequentialGroup()
                                .addComponent(cepDif, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEnd3Layout.createSequentialGroup()
                                .addComponent(jLabel78)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(estadoDif))))
                .addContainerGap())
        );
        pEnd3Layout.setVerticalGroup(
            pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnd3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(jLabel67)
                    .addComponent(jLabel68))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pEnd3Layout.createSequentialGroup()
                        .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel69)
                            .addComponent(jLabel70)
                            .addComponent(jLabel71))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEnd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bairroDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cepDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)))
                    .addGroup(pEnd3Layout.createSequentialGroup()
                        .addComponent(jLabel78)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel72.setText("1º Ponto de Referência:");

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel73.setText("1º Pessoa Autorizada:");

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel74.setText("1º Telefone da Pessoa Autorizada:");

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel75.setText("2º Ponto de Referência:");

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel76.setText("2º Pessoa Autorizada:");

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel77.setText("2º Telefone da Pessoa Autorizada:");

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel79.setText("Telefone de Contato 2:");

        javax.swing.GroupLayout tDadosC1Layout = new javax.swing.GroupLayout(tDadosC1);
        tDadosC1.setLayout(tDadosC1Layout);
        tDadosC1Layout.setHorizontalGroup(
            tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tDadosC1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tDadosC1Layout.createSequentialGroup()
                        .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpftit)
                            .addGroup(tDadosC1Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datanas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56))
                        .addContainerGap())
                    .addGroup(tDadosC1Layout.createSequentialGroup()
                        .addComponent(endif)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tDadosC1Layout.createSequentialGroup()
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addComponent(jLabel14)
                            .addComponent(opField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(271, 271, 271)
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusVenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(tDadosC1Layout.createSequentialGroup()
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel79))
                        .addGap(18, 18, 18)
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tDadosC1Layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addGap(0, 339, Short.MAX_VALUE))
                            .addComponent(maenome))
                        .addContainerGap())
                    .addGroup(tDadosC1Layout.createSequentialGroup()
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pEnd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pEnd3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tDadosC1Layout.createSequentialGroup()
                                .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel73)
                                    .addComponent(jLabel72)
                                    .addComponent(pref1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pau1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ptel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel74))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel75)
                                    .addComponent(jLabel76)
                                    .addComponent(pref2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pau2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ptel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel77))))
                        .addContainerGap())))
        );
        tDadosC1Layout.setVerticalGroup(
            tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tDadosC1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel53)
                    .addComponent(statusVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tDadosC1Layout.createSequentialGroup()
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpftit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tDadosC1Layout.createSequentialGroup()
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel79)
                            .addComponent(jLabel58))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pEnd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endif, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pEnd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tDadosC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tDadosC1Layout.createSequentialGroup()
                        .addComponent(jLabel72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel73)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel74)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ptel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tDadosC1Layout.createSequentialGroup()
                        .addComponent(jLabel75)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel76)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel77)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ptel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        tVendas.addTab("Dados do Cliente:", tDadosC1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Região da venda:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Data da Venda:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Campanha:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Resultado do Crivo:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Plano:");

        dVenda.setEditable(false);

        resCrivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        resCrivo.setToolTipText("");

        estadoV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RJ/ES", "MG/BA/SE/DF/RS", "Demais estados", " " }));

        planoV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Controle B", "Controle A", "Controle Light", "Pos A", "Pos B", "Pos C", "Pos D" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Vencimento:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Tipo de boleto:");

        vencV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia 07", "Dia 10", "Dia 15", "Dia 20" }));
        vencV.setSelectedIndex(-1);

        tipoV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Físico", "Digital" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("E-Mail:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Protocolo do Crivo:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Operadora de Origem:");

        opV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opV.setSelectedIndex(-1);

        portabilidadeV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        portabilidadeV.setText("Optou portabilidade");
        portabilidadeV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portabilidadeVActionPerformed(evt);
            }
        });

        nPortab.setEnabled(false);
        nPortab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPortabActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Número da Portabilidade:");
        jLabel15.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Print do score:");

        print.setText("Carregar Imagem");

        jPanel3.setBackground(new java.awt.Color(218, 218, 218));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vincular Dependentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        adcDependente.setText("Adicionar");
        adcDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcDependenteActionPerformed(evt);
            }
        });

        removerDependente.setText("Remover");
        removerDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerDependenteActionPerformed(evt);
            }
        });

        editarDependente.setText("Editar");
        editarDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDependenteActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Tipo:");

        depTipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Número Celular:");

        numCelDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCelDependenteActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Tipo da Conta:");

        tipoContaDepComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Tipo do Plano:");

        tipoPlanoDepComboBOx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("E-Mail:");

        emailDependTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailDependTextFieldActionPerformed(evt);
            }
        });

        dependTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Número Celular", "Tipo da Conta", "Tipo do Plano", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dependTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        dependTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dependTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dependTable);
        dependTable.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depTipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(numCelDependente, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(tipoContaDepComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(tipoPlanoDepComboBOx, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(adcDependente)
                                .addGap(10, 10, 10)
                                .addComponent(removerDependente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editarDependente))
                            .addComponent(jLabel21)
                            .addComponent(emailDependTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adcDependente)
                    .addComponent(removerDependente)
                    .addComponent(editarDependente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depTipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numCelDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoContaDepComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoPlanoDepComboBOx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailDependTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fidelizacaoA1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fidelizacaoA1.setText("Optou fidelização anual");
        fidelizacaoA1.setActionCommand("");
        fidelizacaoA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fidelizacaoA1ActionPerformed(evt);
            }
        });

        redesSociasA1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        redesSociasA1.setText("Optou redes sociais");
        redesSociasA1.setActionCommand("");
        redesSociasA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redesSociasA1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tDadosVLayout = new javax.swing.GroupLayout(tDadosV);
        tDadosV.setLayout(tDadosVLayout);
        tDadosVLayout.setHorizontalGroup(
            tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tDadosVLayout.createSequentialGroup()
                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tDadosVLayout.createSequentialGroup()
                        .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tDadosVLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(tDadosVLayout.createSequentialGroup()
                                        .addComponent(portabilidadeV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nPortab))
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(tDadosVLayout.createSequentialGroup()
                                        .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(dVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(estadoV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8)
                                    .addComponent(planoV, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)))
                            .addGroup(tDadosVLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 50, Short.MAX_VALUE)
                        .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(tDadosVLayout.createSequentialGroup()
                                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(tDadosVLayout.createSequentialGroup()
                                        .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12))
                                        .addGap(94, 94, 94))
                                    .addGroup(tDadosVLayout.createSequentialGroup()
                                        .addComponent(vencV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(7, 7, 7)))
                                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoV, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10)))
                            .addGroup(tDadosVLayout.createSequentialGroup()
                                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(campV, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(resCrivo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tDadosVLayout.createSequentialGroup()
                                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(print, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(protocolo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(opV, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fidelizacaoA1)
                                    .addComponent(redesSociasA1))))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(tDadosVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tDadosVLayout.setVerticalGroup(
            tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tDadosVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(5, 5, 5)
                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resCrivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vencV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(protocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tDadosVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portabilidadeV)
                    .addComponent(nPortab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print)
                    .addComponent(fidelizacaoA1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redesSociasA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        tVendas.addTab("Dados da Venda:", tDadosV);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        tVendas.addTab("Consulta de Vendas:", jPanel2);

        jButton1.setText("Enviar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Voltar");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tVendas)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int entregaAlternativa, optouPortabilidade, aceitoCrivo, fidelizadaAno, optouAppsDataFree, boletoDigital, vendaAceitaCliente;
        String nomeOperador, dataVenda, regiaoVenda, planoEscolhido, nomeCliente, cpfCliente, telefone1Cliente, telefone2Cliente, dataNascCliente, 
                nomeMaeCliente, cepCliente, cidadeCliente, estadoCliente, logradouroCliente, numeroCliente, complementoCliente, bairroCliente, 
                pontoReferencia1, pontoReferencia2, nomePessoaAutorizada1, nomePessoaAutorizada2, telefonePessoaAutorizada1, telefonePessoaAutorizada2, 
                email, portabilidadeDDD, dataVencimento, cepAlternativo, estadoAlternativo, cidadeAlternativa, bairroAlternativo, logradouroAlternativo, 
                numeroAlternativo, complementoAlternativo;
        int qtdChipsEnviar;
        
        entregaAlternativa = 0;
        optouPortabilidade = 0;
        aceitoCrivo = 0;
        fidelizadaAno = 0;
        optouAppsDataFree = 0;
        boletoDigital = 0;
        vendaAceitaCliente = 0;
        
        pontoReferencia1 = pref1.getText();
        pontoReferencia2 = pref2.getText();
        nomePessoaAutorizada1 = pau1.getText();
        nomePessoaAutorizada2 = pau2.getText();
        telefonePessoaAutorizada1 = ptel1.getText();
        telefonePessoaAutorizada2 = ptel2.getText();
        nomeOperador = nome;
        dataVenda = ZonedDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE);
        regiaoVenda = estadoV.getItemAt(statusVenda.getSelectedIndex());
        planoEscolhido = planoV.getItemAt(planoV.getSelectedIndex());
        nomeCliente = cliente.getText();
        cpfCliente = this.cpftit.getText();
        telefone1Cliente = tel.getText();
        telefone2Cliente = tel1.getText();
        dataNascCliente = datanas.getText();
        nomeMaeCliente = maenome.getText();
        cepCliente = cep.getText();
        cidadeCliente = this.cidade.getText();
        estadoCliente = this.estado.getText();
        logradouroCliente = this.end.getText();
        numeroCliente = this.num.getText();
        complementoCliente = this.comp.getText();
        bairroCliente = this.bairro.getText();
        email = this.email.getText();
        portabilidadeDDD = nPortab.getText();
        dataVencimento = vencV.getItemAt(vencV.getSelectedIndex());
        cepAlternativo = cepDif.getText();
        estadoAlternativo = this.estadoDif.getText();
        cidadeAlternativa = this.cidDif.getText();
        bairroAlternativo = this.bairroDif.getText();
        logradouroAlternativo = endDif.getText();
        numeroAlternativo = this.nDif.getText();
        complementoAlternativo = this.compDif.getText();
        qtdChipsEnviar = dependTable.getRowCount();
        
        if(portabilidadeV.isSelected())
            optouPortabilidade = 1;
        if(endif.isSelected())
            entregaAlternativa = 1;
        if(resCrivo.getItemAt(resCrivo.getSelectedIndex()).equals("Sim"))
            aceitoCrivo = 1;
        if(fidelizacaoA1.isSelected())
            fidelizadaAno = 1;
        if(redesSociasA1.isSelected())
            optouAppsDataFree = 1;
        if(tipoV.getItemAt(tipoV.getSelectedIndex()).equals("Digital"))
            boletoDigital = 1;
        if(statusVenda.getItemAt(statusVenda.getSelectedIndex()).equals("Aceita pelo cliente"));
            vendaAceitaCliente = 1;
            
        String qry = "INSERT INTO `teleconectividade`.`vendas` (`nomeOperador`, "
                + "`dataVenda`, `regiaoVenda`, `planoEscolhido`, `nomeCliente`, "
                + "`cpfCliente`, `telefone1Cliente`, `telefone2Cliente`, `dataNascCliente`, "
                + "`nomeMaeCliente`, `statusCrivo`, `fidelizadaAno`, `optouAppsDataFree`, "
                + "`cepCliente`, `cidadeCliente`, `estadoCliente`, `logradouroCliente`, "
                + "`numeroCliente`, `complementoCliente`, `bairroCliente`, `pontoReferencia1`, "
                + "`pontoReferencia2`, `nomePessoaAutorizada1`, `nomePessoaAutorizada2`, "
                + "`telefonePessoaAutorizada1`, `telefonePessoaAutorizada2`, `quantidadeChipsAEnviar`, "
                + "`boletoDigital`, `email`, `optouPortabilidade`, `portabilidadeDDD`, `dataVencimento`, "
                + "`aceite`, `cepAlternativo`, `estadoAlternativo`, `cidadeAlternativa`, `bairroAlternativo`, "
                + "`logradouroAlternativo`, `numeroAlternativo`, `complementoAlternativo`, `enderecoAlternativo`) "
                + "VALUES ('"+nomeOperador+"', '"+dataVenda+"', '"+regiaoVenda+"', '"+planoEscolhido+"', '"+nomeCliente+"', '"+cpfCliente+"', "
                + "'"+telefone1Cliente+"', '"+telefone2Cliente+"', '"+dataNascCliente+"', '"+nomeMaeCliente+"', '"+aceitoCrivo+"', "
                + "'"+fidelizadaAno+"', '"+optouAppsDataFree+"', '"+cepCliente+"', '"+cidadeCliente+"', '"+estadoCliente+"', '"+logradouroCliente+"', "
                + "'"+numeroCliente+"', '"+complementoCliente+"', '"+bairroCliente+"', '"+pontoReferencia1+"', '"+pontoReferencia2+"', "
                + "'"+nomePessoaAutorizada1+"', '"+nomePessoaAutorizada2+"', '"+telefonePessoaAutorizada1+"', '"+telefonePessoaAutorizada2+"', "
                + "'"+qtdChipsEnviar+"', '"+boletoDigital+"', '"+email+"', '"+optouPortabilidade+"', '"+portabilidadeDDD+"', '"+dataVencimento+"', "
                + "'"+vendaAceitaCliente+"', '"+cepAlternativo+"', '"+estadoAlternativo+"', '"+cidadeAlternativa+"', "
                + "'"+bairroAlternativo+"', '"+logradouroAlternativo+"', '"+numeroAlternativo+"', '"+complementoAlternativo+"', '"+entregaAlternativa+"')";
        
        
       
        
        try {
            dba.execute(qry);
            JOptionPane.showMessageDialog(this, "Pedido realizado com sucesso");
        } catch (SQLException ex) {
            Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            dba.closeConnnection();
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void redesSociasA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redesSociasA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redesSociasA1ActionPerformed

    private void fidelizacaoA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidelizacaoA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fidelizacaoA1ActionPerformed

    private void emailDependTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailDependTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailDependTextFieldActionPerformed

    private void numCelDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCelDependenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCelDependenteActionPerformed

    private void nPortabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPortabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPortabActionPerformed

    private void portabilidadeVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portabilidadeVActionPerformed
        if(portabilidadeV.isSelected())
        nPortab.setEnabled(true);
        else
        nPortab.setEnabled(false);
    }//GEN-LAST:event_portabilidadeVActionPerformed

    private void jButton5jLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jButton5jLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5jLabel68VetoableChange

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String qry = "";
        String cep = "";
        String endereco = "";
        String bairro = "";
        String cidade = "";
        String estado = "";
        int bairroCod = -1;
        int cidCod = -1;
        int ufCod = -1;

        cep = this.cepDif.getText();

        try {
            qry = "SELECT endereco_logradouro, bairro_codigo FROM endereco WHERE (endereco_cep = " +cep+ " ) ";
            ResultSet rs = dba.execQry(qry);
            if(rs.next()){
                endereco = rs.getString("endereco_logradouro");
                bairroCod = rs.getInt("bairro_codigo");
            }
            qry = "SELECT bairro_descricao, cidade_codigo FROM bairro WHERE (bairro_codigo = " +bairroCod+ " ) ";
            rs = dba.execQry(qry);
            if(rs.next()) {
                bairro = rs.getString("bairro_descricao");
                cidCod = rs.getInt("cidade_codigo");
            }
            qry = "SELECT cidade_descricao, uf_codigo FROM cidade WHERE (cidade_codigo = " +cidCod+ " ) ";
            rs = dba.execQry(qry);
            if(rs.next()) {
                cidade = rs.getString("cidade_descricao");
                ufCod = rs.getInt("uf_codigo");
            }
            qry = "SELECT uf_descricao FROM uf WHERE (uf_codigo = " +ufCod+ " ) ";
            rs = dba.execQry(qry);
            if(rs.next()) {
                estado = rs.getString("uf_descricao");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.endDif.setText(endereco);
        this.bairroDif.setText(bairro);
        this.cidDif.setText(cidade);
        this.estadoDif.setText(estado);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cepDifjLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cepDifjLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cepDifjLabel68VetoableChange

    private void jLabel71jLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jLabel71jLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel71jLabel68VetoableChange

    private void cidDifjLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cidDifjLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cidDifjLabel68VetoableChange

    private void jLabel70jLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jLabel70jLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel70jLabel68VetoableChange

    private void bairroDifjLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_bairroDifjLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroDifjLabel68VetoableChange

    private void jLabel69jLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jLabel69jLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel69jLabel68VetoableChange

    private void compDifjLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_compDifjLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_compDifjLabel68VetoableChange

    private void nDifjLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_nDifjLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nDifjLabel68VetoableChange

    private void nDifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nDifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nDifActionPerformed

    private void jLabel67jLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jLabel67jLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel67jLabel68VetoableChange

    private void endDifjLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_endDifjLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_endDifjLabel68VetoableChange

    private void jLabel66jLabel68VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jLabel66jLabel68VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel66jLabel68VetoableChange

    private void endifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endifActionPerformed
        if(endif.isSelected()) {
            endDif.setEnabled(true);
            nDif.setEnabled(true);
            compDif.setEnabled(true);
            bairroDif.setEnabled(true);
            cidDif.setEnabled(true);
            cepDif.setEnabled(true);
            jButton5.setEnabled(true);
            estadoDif.setEnabled(true);
            pEnd3.setBackground(Color.WHITE);
        } else {
            endDif.setEnabled(false);
            nDif.setEnabled(false);
            compDif.setEnabled(false);
            bairroDif.setEnabled(false);
            cidDif.setEnabled(false);
            cepDif.setEnabled(false);
            jButton5.setEnabled(false);
            estadoDif.setEnabled(false);
            pEnd3.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_endifActionPerformed

    private void endifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endifMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_endifMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String qry = "";
        String cep = "";
        String endereco = "";
        String bairro = "";
        String cidade = "";
        String estado = "";
        int bairroCod = -1;
        int cidCod = -1;
        int ufCod = -1;

        cep = this.cep.getText();

        try {
            qry = "SELECT endereco_logradouro, bairro_codigo FROM endereco WHERE (endereco_cep = " +cep+ " ) ";
            ResultSet rs = dba.execQry(qry);
            if(rs.next()){
                endereco = rs.getString("endereco_logradouro");
                bairroCod = rs.getInt("bairro_codigo");
            }
            qry = "SELECT bairro_descricao, cidade_codigo FROM bairro WHERE (bairro_codigo = " +bairroCod+ " ) ";
            rs = dba.execQry(qry);
            if(rs.next()) {
                bairro = rs.getString("bairro_descricao");
                cidCod = rs.getInt("cidade_codigo");
            }
            qry = "SELECT cidade_descricao, uf_codigo FROM cidade WHERE (cidade_codigo = " +cidCod+ " ) ";
            rs = dba.execQry(qry);
            if(rs.next()) {
                cidade = rs.getString("cidade_descricao");
                ufCod = rs.getInt("uf_codigo");
            }
            qry = "SELECT uf_descricao FROM uf WHERE (uf_codigo = " +ufCod+ " ) ";
            rs = dba.execQry(qry);
            if(rs.next()) {
                estado = rs.getString("uf_descricao");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.end.setText(endereco);
        this.bairro.setText(bairro);
        this.cidade.setText(cidade);
        this.estado.setText(estado);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numActionPerformed

    private void adcDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcDependenteActionPerformed
        String tipo = depTipoComboBox.getItemAt(depTipoComboBox.getSelectedIndex());
        String num = numCelDependente.getText();
        String tipoConta = tipoContaDepComboBox.getItemAt(tipoContaDepComboBox.getSelectedIndex());
        String tipoPlano = tipoPlanoDepComboBOx.getItemAt(tipoPlanoDepComboBOx.getSelectedIndex());
        String email = emailDependTextField.getText();
        
        Object[] rowData = new Object[5];
        rowData[0] = tipo;
        rowData[1] = num;
        rowData[2] = tipoConta;
        rowData[3] = tipoPlano;
        rowData[4] = email;
        
        DefaultTableModel tableModel = (DefaultTableModel) dependTable.getModel();
        tableModel.addRow(rowData);
        dependTable.setModel(tableModel);
        emailDependTextField.setText("");
        numCelDependente.setText("");
    }//GEN-LAST:event_adcDependenteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void removerDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerDependenteActionPerformed
        int selectedRowIndex = dependTable.getSelectedRow();
        DefaultTableModel tableModel = (DefaultTableModel) dependTable.getModel();
        
        tableModel.removeRow(selectedRowIndex);
    }//GEN-LAST:event_removerDependenteActionPerformed

    private void dependTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dependTableMouseClicked
        int selectedRowIndex = dependTable.getSelectedRow();
        int contaCombidx = -1, planoCombidx = -1, tipoCombidx = -1; 
        
        DefaultTableModel tableModel = (DefaultTableModel) dependTable.getModel();
        
        String tipo = (String) tableModel.getValueAt(selectedRowIndex, 0);
        String num = (String) tableModel.getValueAt(selectedRowIndex, 1);
        String tipoConta = (String) tableModel.getValueAt(selectedRowIndex, 2);
        String tipoPlano = (String) tableModel.getValueAt(selectedRowIndex, 3);
        String email = (String) tableModel.getValueAt(selectedRowIndex, 4);
        
        for(int i = 0 ; i < depTipoComboBox.getItemCount() ; i++)
            if(tipo.equals(depTipoComboBox.getItemAt(i)))
                tipoCombidx = i;
        
        for(int i = 0 ; i < tipoContaDepComboBox.getItemCount() ; i++)
            if(tipoConta.equals(tipoContaDepComboBox.getItemAt(i)))
                contaCombidx = i;
     
        for(int i = 0 ; i < tipoPlanoDepComboBOx.getItemCount() ; i++)
            if(tipoPlano.equals(tipoPlanoDepComboBOx.getItemAt(i)))
                planoCombidx = i;
        
        depTipoComboBox.setSelectedIndex(tipoCombidx);
        tipoContaDepComboBox.setSelectedIndex(contaCombidx);
        tipoPlanoDepComboBOx.setSelectedIndex(planoCombidx);
        emailDependTextField.setText(email);
        numCelDependente.setText(num);
    }//GEN-LAST:event_dependTableMouseClicked

    private void editarDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDependenteActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) dependTable.getModel();
        int rowSelectedIndex = dependTable.getSelectedRow();
        
        tableModel.removeRow(rowSelectedIndex);
        
        String tipo = depTipoComboBox.getItemAt(depTipoComboBox.getSelectedIndex());
        String num = numCelDependente.getText();
        String tipoConta = tipoContaDepComboBox.getItemAt(tipoContaDepComboBox.getSelectedIndex());
        String tipoPlano = tipoPlanoDepComboBOx.getItemAt(tipoPlanoDepComboBOx.getSelectedIndex());
        String email = emailDependTextField.getText();
        
        Object[] rowData = new Object[5];
        rowData[0] = tipo;
        rowData[1] = num;
        rowData[2] = tipoConta;
        rowData[3] = tipoPlano;
        rowData[4] = email;
        
        tableModel.addRow(rowData);
        dependTable.setModel(tableModel);
        emailDependTextField.setText("");
        numCelDependente.setText("");
        
        dependTable.setModel(tableModel);
        
    }//GEN-LAST:event_editarDependenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas(ramal, nome).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adcDependente;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField bairroDif;
    private javax.swing.JComboBox<String> campV;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cepDif;
    private javax.swing.JTextField cidDif;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField comp;
    private javax.swing.JTextField compDif;
    private javax.swing.JTextField cpftit;
    private javax.swing.JTextField dVenda;
    private javax.swing.JTextField datanas;
    private javax.swing.JComboBox<String> depTipoComboBox;
    private javax.swing.JTable dependTable;
    private javax.swing.JButton editarDependente;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emailDependTextField;
    private javax.swing.JTextField end;
    private javax.swing.JTextField endDif;
    private javax.swing.JCheckBox endif;
    private javax.swing.JTextField estado;
    private javax.swing.JTextField estadoDif;
    private javax.swing.JComboBox<String> estadoV;
    private javax.swing.JCheckBox fidelizacaoA1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField maenome;
    private javax.swing.JTextField nDif;
    private javax.swing.JTextField nPortab;
    private javax.swing.JTextField num;
    private javax.swing.JTextField numCelDependente;
    private javax.swing.JTextField opField;
    private javax.swing.JComboBox<String> opV;
    private javax.swing.JPanel pEnd2;
    private javax.swing.JPanel pEnd3;
    private javax.swing.JTextField pau1;
    private javax.swing.JTextField pau2;
    private javax.swing.JComboBox<String> planoV;
    private javax.swing.JCheckBox portabilidadeV;
    private javax.swing.JTextField pref1;
    private javax.swing.JTextField pref2;
    private javax.swing.JButton print;
    private javax.swing.JTextField protocolo;
    private javax.swing.JTextField ptel1;
    private javax.swing.JTextField ptel2;
    private javax.swing.JCheckBox redesSociasA1;
    private javax.swing.JButton removerDependente;
    private javax.swing.JComboBox<String> resCrivo;
    private javax.swing.JComboBox<String> statusVenda;
    private javax.swing.JPanel tDadosC1;
    private javax.swing.JPanel tDadosV;
    private javax.swing.JTabbedPane tVendas;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField tel1;
    private javax.swing.JComboBox<String> tipoContaDepComboBox;
    private javax.swing.JComboBox<String> tipoPlanoDepComboBOx;
    private javax.swing.JComboBox<String> tipoV;
    private javax.swing.JComboBox<String> vencV;
    // End of variables declaration//GEN-END:variables
}
